# Generated by Django 4.0.5 on 2022-06-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=30)),
                ('developer', models.CharField(max_length=30)),
                ('price', models.FloatField(max_length=6)),
            ],
            options={
                'verbose_name': 'juego',
                'verbose_name_plural': 'juegos',
            },
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('descrpition', models.CharField(max_length=200)),
                ('length', models.IntegerField()),
                ('genre', models.CharField(max_length=30)),
                ('director', models.CharField(blank=True, max_length=40, null=True)),
                ('cast', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'pelicula',
                'verbose_name_plural': 'peliculas',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('descrpition', models.CharField(max_length=200)),
                ('seasons', models.IntegerField()),
                ('genre', models.CharField(max_length=30)),
                ('director', models.CharField(blank=True, max_length=40, null=True)),
                ('cast', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'serie',
                'verbose_name_plural': 'series',
            },
        ),
    ]
