# Generated by Django 4.0.5 on 2022-06-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='descrpition',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='descrpition',
            new_name='description',
        ),
    ]
