# Generated by Django 4.0.5 on 2022-06-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_rename_descrpition_peliculas_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='price',
            field=models.FloatField(),
        ),
    ]
