# Generated by Django 4.0.5 on 2022-06-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_alter_games_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='cast',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
