# Generated by Django 4.0.5 on 2022-07-03 22:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0014_commentserie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default=str, max_length=200)),
                ('text', models.TextField(default=str, max_length=1000)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='peliculas.games')),
            ],
        ),
    ]
