# Generated by Django 4.0.5 on 2022-07-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0015_commentgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='peliculas_image',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_peliculas'),
        ),
    ]
