# Generated by Django 4.0.5 on 2022-07-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0017_games_games_image_series_series_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='games_image',
        ),
        migrations.AddField(
            model_name='games',
            name='game_image',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_games'),
        ),
    ]
